### ISSUE TITLE
Support for ARCH specific dind image build

### ISSUE THREAD

**Issue by guirish** [projectcalico/dind#9]
Need to add support to build dind images based on ARCH specification in build.sh file.

**Comment by guirish** [comment]
Hi @fasaxc, conditional dind image build based on ARCH's feature need to be added in build.sh file.

**Comment by tmjd** [comment]
@fasaxc do we still use this for anything?

**Comment by fasaxc** [comment]
I don't know.  Maybe some of the calico/node tests?
